image:
  # - Visual Studio 2013
  # - Visual Studio 2015
  - Visual Studio 2017
  - Ubuntu

platform: x64

environment:
  matrix:
        # - nodejs_version: "8"
        - nodejs_version: "9"
        # - nodejs_version: "10"
        # - nodejs_version: "node"

build: off

install:
 - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
 - ps: Update-AppveyorBuild -Version "$env:package_version.$env:APPVEYOR_BUILD_NUMBER"
 - cmd: powershell -command "Install-Product node $env:nodejs_version"
 - sh: nvm install $nodejs_version
 - npm install
