image:
  Visual Studio 2015
  # - Ubuntu

platform: x64

environment:
  matrix:
        - nodejs_version: "Current"

build: off
deploy: off

install:
 - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
 - ps: Update-AppveyorBuild -Version "$env:package_version.$env:APPVEYOR_BUILD_NUMBER"
 - cmd: powershell -command "Install-Product node $env:nodejs_version"
 - sh: nvm install $nodejs_version
 - npm install


test_script:
  - node --version
  - npm test